User.create(user_name: "harsh",password:"1234")
User.create(user_name: "abhishek",password:"1234")
User.create(user_name: "anhsul",password:"1234")
User.create(user_name: "chiku",password:"1234")
User.create(user_name: "rahul",password:"1234")
User.create(user_name: "diwakar",password:"1234")

Message.create(body:"hey message 1",user_id: User.first.id)
Message.create(body:"hey message 2",user_id: User.second.id)
Message.create(body:"hey message 3",user_id: User.first.id)
Message.create(body:"hey message 4",user_id: User.third.id)
Message.create(body:"hey message 5",user_id: User.first.id)
Message.create(body:"hey message 6",user_id: User.last.id)
Message.create(body:"hey message 7",user_id: User.second.id)
Message.create(body:"hey message 8",user_id: User.third.id)
